[mqtt]

# ID used when connecting MQTT client, needs to be unique across MQTT clients connected to the broker
id = "neato-mqtt"

# Domain name / IP address and port of the MQTT broker
# host = "localhost" # in case of local broker
host = "mosquitto"
port = 1883

# MQTT topic where updates will be published
topic = "home/devices/neato/{id}"

# received state to the devices
topic_set = "home/devices/neato/{id}/set"

[neato]
username = "your_email@address.com"
password = "password"