[mqtt]

# ID used when connecting MQTT client, needs to be unique across MQTT clients connected to the broker
id = "neato-mqtt"

# Domain name / IP address and port of the MQTT broker
# host = "your_broker_address" # defaults to "localhost"
# port = 1883 # defaults to 1883

# MQTT topic where updates will be published
# Uncomment if you want to change the topic
# topic = "home/devices/neato/{id}"

# received state to the devices
# Uncomment if you want to change the set topic
# set_topic = "home/devices/neato/{id}/set"

[neato]
username = "your_email@address.com"
password = "password"
# dry_run = false # uncomment to enable dry run mode